### ISSUE TITLE
Driver for 7.3?

### ISSUE THREAD

**Issue by Baseult** [dmarov/chamd#1]
Hey awesome work.

I tried to make my own 7.3 driver undetected but works only for a few games, your version works for most games that I tried so far.

Are you going to work on the 7.3 driver too?
Thanks a lot for your work :)

**Comment by dmarov** [comment]
Thanks. I plan to upgrade it from 7.3 in near future. I think official renamed 7.3 version should be detected by EAC already.

> but works only for a few games

I'm curious for which one it doesn't work? If it's free, then I might consider it as my next target.

**Comment by YMY1666527646** [comment]
> Thanks. I plan to upgrade it from 7.3 in near future. I think official renamed 7.3 version should be detected by EAC already.
> 
> > but works only for a few games
> 
> I'm curious for which one it doesn't work? If it's free, then I might consider it as my next target.
![CE](https://user-images.githubusercontent.com/84628110/148646075-d17c4a6e-f9ca-412d-b0a9-83a75c7ba5f4.png)

Does not support Windows 10 1909?
I reinstalled windows 10 half a month ago
Windows 10 1809 has been used before, and this problem has not occurred since its release
Open all processes are the same

**Comment by dmarov** [comment]
> I think official renamed 7.3 version should be detected by EAC already.

I was wrong: 01/12/2022 EAC - renamed target of DBK 7.3 still works with RoboCraft at least
